# Pane/sesion manipulation
## Session management
bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind K confirm kill-session

## Use same dir in new pane
bind c new-window        -c "#{pane_current_path}"
bind % split-window   -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Movement
## Vim movememnt
set -g status-key vi
setw -g mode-keys vi

## Moving through panes with vim "arrows"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

## Handling of mouse
set -g mouse on

# Styling
## Coloring
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

## Theme
set -g @catppuccin_flavor 'frappe'
set -g @catppuccin_window_status_style "rounded"

run '~/.tmux/plugins/catppuccin/tmux/catppuccin.tmux'

# Plugin management
## Definitions
### Plugin management
set -g @plugin 'tmux-plugins/tpm'


## Initialize

run '~/.tmux/plugins/tpm/tpm'

