# Pane/sesion manipulation
## Session management
bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind K confirm kill-session

## Use same dir in new pane
bind c new-window        -c "#{pane_current_path}"
bind % split-window   -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Movement
## Vim movememnt
set -g status-key vi
setw -g mode-keys vi

## Moving through panes with vim "arrows"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

## Handling of mouse
set -g mouse on
